"""
NullHunter API Gateway & Master Orchestrator
=====================================================================

This module serves as the primary Facade and Universal Middleware for the 
NullHunter framework. It abstracts away the complex Directed Acyclic Graph (DAG) 
of the internal nodes (Flattener, Optimizer, Scanner, Engine) and exposes a clean, 
highly configurable API for the user.

Key Enterprise Features:
1. Autonomous Short-Circuiting (The Self-Firing Protocol): Workers actively 
   terminate themselves during Pass 1 if deemed unnecessary, resulting in brutal 
   O(1) execution bypasses for Pass 2.
2. Loop-Less MapReduce Architecture: Employs UniversalParallelRunner during Pass 1 
   to bypass Python's Global Interpreter Lock (GIL) and generate 100% accurate 
   statistical blueprints across the entire population.
3. The Transparent Tool Decorator (`@auto_shape_handler`): Enables external ML tools 
   to seamlessly consume and return 3D MultiIndex data while executing purely on flat arrays.
4. Smart Buffer Override Logic: Defers RAM constraints to the Loader unless explicitly 
   overridden by the user (The "Boss" logic).
"""

import time
import copy
import logging
import pandas as pd
from enum import Enum
from pathlib import Path
from functools import wraps
from typing import Dict, Any, Optional, Union, Callable

# ==========================================
# CONFIGURATION & EXCEPTIONS
# ==========================================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | [%(levelname)s] NULLHUNTER_CORE: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)


class NullHunterValidationError(Exception):
    """Raised when the user provides invalid parameters or blueprint schemas."""
    pass

class ExecutionMode(str, Enum):
    """Enumeration for strict execution mode validation."""
    AUTO = "auto"
    STRICT = "strict"
    HYBRID = "hybrid"


# ==========================================
# INTERNAL UTILITIES
# ==========================================
def _deep_merge_blueprints(ai_blueprint: Dict, user_blueprint: Dict) -> Dict:
    """
    Intelligently merges the AI-generated blueprint with user-defined overrides.
    
    Args:
        ai_blueprint (Dict): The comprehensive blueprint generated by the Scanner.
        user_blueprint (Dict): The specific overrides provided by the user.
        
    Returns:
        Dict: A unified execution blueprint where human rules overwrite AI rules.
    """
    merged = copy.deepcopy(ai_blueprint)
    for col, rules in user_blueprint.items():
        if col in merged:
            merged[col].update(rules) 
        else:
            merged[col] = rules       
    return merged


# ==========================================
# UNIVERSAL TOOL MIDDLEWARE
# ==========================================
def auto_shape_handler(func: Callable) -> Callable:
    """
    The Smart Decorator for `nh.tools.*` ecosystem.
    
    Acts as an independent interceptor for analytical functions. If a 3D dataset 
    is passed to a tool wrapped in this decorator, it automatically flattens the 
    data, executes the algorithm, and reconstructs the 3D matrix seamlessly. 
    If the data is natively 2D, it bypasses flattening instantly via O(1) checks.

    Args:
        func (Callable): The tool function to wrap (e.g., `knn_imputer`).

    Returns:
        Callable: The wrapped, dimensionally-agnostic tool.
    """
    @wraps(func)
    def wrapper(data: pd.DataFrame, bypass_flattening: bool = False, *args, **kwargs):
        if bypass_flattening:
            logger.debug("Decorator bypass active. Injecting raw data into tool.")
            return func(data, *args, **kwargs)
            
        from nullhunter.nodes.flattener import SchemaFlattener
        flattener = SchemaFlattener()
        
        # Self-Firing Protocol
        _, keep_flattener = flattener.evaluate(data, user_bypass=False)
        
        if not keep_flattener:
            return func(data, *args, **kwargs)
            
        # Transparent Shape Shifting
        flat_data = flattener.transform(data)
        processed_data = func(flat_data, *args, **kwargs)
        
        from nullhunter.nodes.reconstructor import SchemaReconstructor
        reconstructor = SchemaReconstructor()
        return reconstructor.rebuild(
            processed_data, 
            flattener.schema_blueprint.get('reconstruction_mapping', {})
        )
        
    return wrapper


# ==========================================
# ISOLATED PASS-1 WORKER (For Loop-Less MapReduce)
# ==========================================
def _pass1_discovery_worker(
    chunk: pd.DataFrame, 
    keep_flat: bool, 
    keep_opt: bool, 
    flat_blueprint: Dict, 
    opt_headers: list
) -> Dict[str, Any]:
    """
    Isolated worker for Pass-1 Map phase. Applies O(1) bypasses instantly.
    
    Args:
        chunk (pd.DataFrame): The raw data chunk.
        keep_flat (bool): Flag to keep Flattener active.
        keep_opt (bool): Flag to keep Optimizer active.
        flat_blueprint (Dict): Asset 1 (Master Ledger).
        opt_headers (list): Asset 2 (Optimized Metadata).
        
    Returns:
        Dict[str, Any]: Statistical moments for the chunk via Scanner.
    """
    # 1. Brutal O(1) Bypasses
    if keep_flat:
        from nullhunter.nodes.flattener import SchemaFlattener
        flattener = SchemaFlattener(memory_safe_copy=True)
        flattener.schema_blueprint = flat_blueprint
        chunk = flattener.transform(chunk)
        
    if keep_opt:
        chunk.columns = opt_headers
        
    # 2. Extract Math Moments (Map Phase)
    from nullhunter.nodes.scanner import extract_chunk_statistics
    return extract_chunk_statistics(chunk)




# ==========================================
# THE GATEWAY FACADE
# ==========================================
logger = logging.getLogger(__name__)

def purify(
    source: Union[str, Path, Any], 
    destination: Union[str, Path], 
    mode: Union[str, 'ExecutionMode'] = 'ExecutionMode.AUTO',
    blueprint: Optional[Dict[str, Dict[str, Any]]] = None,
    bypass_flattening: bool = False,
    bypass_optimization: bool = False,
    keep_optimized_headers: bool = False,
    fail_fast: bool = False,
    max_cores: Optional[int] = None,
    buffer_size_mb: Optional[int] = None,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    The Supreme API Gateway and Master Orchestrator for the NullHunter Framework.

    Orchestrates the massive Dual-Pass architecture. Phase 1 executes a Loop-Less 
    MapReduce discovery to generate a statistical AI blueprint and extracts O(1) 
    structural/semantic caches. Phase 2 dispatches these cached assets (Ledgers and 
    Headers) to the Execution Engine, bypassing heavy metadata parsing entirely.

    Args:
        source (Union[str, Path, Any]): Path to the raw input dataset (CSV, JSON, Parquet) 
            or an in-memory DataFrame/DataStream.
        destination (Union[str, Path]): Target filepath where the purified dataset 
            will be atomically flushed.
        mode (Union[str, ExecutionMode], optional): The operational mandate.
            - 'auto': Pure AI-driven blueprint generation.
            - 'strict': Ignores AI, relies entirely on the provided `blueprint`.
            - 'hybrid': Merges AI findings with user-provided `blueprint` overrides.
            Defaults to ExecutionMode.AUTO.
        blueprint (Optional[Dict[str, Dict[str, Any]]], optional): User-defined rules 
            mapping columns to specific analytical actions. Required if mode is 
            STRICT or HYBRID. Defaults to None.
        bypass_flattening (bool, optional): Explicit flag to skip 3D hierarchical 
            resolution, forcing the Flattener to self-terminate. Defaults to False.
        bypass_optimization (bool, optional): Explicit flag to skip semantic header 
            sanitization. Defaults to False.
        keep_optimized_headers (bool, optional): If True, instructs the Phase-3 
            Reconstructor to retain ML-ready flat headers (snake_case) in the final 
            output rather than restoring original semantic names. Defaults to False.
        fail_fast (bool, optional): If True, aborts the parallel pipeline immediately 
            upon the first worker failure. Defaults to False.
        max_cores (Optional[int], optional): Hard concurrency limit for the CPU pool. 
            Defaults to (System Cores - 1).
        buffer_size_mb (Optional[int], optional): The Boss Override. Forces the RAM 
            concatenation buffer to a specific limit, ignoring the Loader's dynamically 
            calculated safe bounds. Defaults to None.
        verbose (bool, optional): Toggles INFO-level execution telemetry. Defaults to True.

    Returns:
        Dict[str, Any]: A comprehensive SaaS-grade telemetry report detailing execution 
            times, memory footprints, and applied transformations.

    Raises:
        NullHunterValidationError: If execution modes conflict with provided parameters.
        ValueError: If the dataloader encounters an entirely empty dataset stream.
    """
    start_time = time.perf_counter()
    if not verbose:
        logger.setLevel(logging.WARNING)

    # 1. Parameter Validation & Mode Resolution
    if isinstance(mode, str):
        try:
            mode = mode.lower()
            # Handle Enum matching safely based on implementation
        except ValueError:
            raise Exception("Invalid mode. Choose: auto, strict, hybrid.")
            
    if mode in ['strict', 'hybrid'] and not blueprint:
        raise Exception("User blueprint required for strict or hybrid execution modes.")

    logger.info(f"Initializing NullHunter Gateway | Mode: [{str(mode).upper()}]")

    # ==========================================
    # PHASE 1: DISCOVERY & CACHE EXTRACTION (O(1) Handoff Setup)
    # ==========================================
    # Lazy Imports: Enforces near-zero framework load time
    from nullhunter.nodes.loader import DataLoader
    from nullhunter.nodes.flattener import SchemaFlattener
    from nullhunter.nodes.optimizer import SchemaOptimizer
    from nullhunter.nodes.scanner import DataScanner, extract_chunk_statistics
    from nullhunter.utils.runner import UniversalParallelRunner
    
    loader = DataLoader(source)
    chunk_generator = loader.get_chunks()
    
    try:
        first_chunk = next(chunk_generator)
    except StopIteration:
        raise ValueError("NullHunter Gateway Error: Cannot purify an empty dataset.")

    # A. Flattener Self-Firing & Shape Ledger Extraction
    flattener = SchemaFlattener(memory_safe_copy=True)
    _, keep_flattener = flattener.evaluate(first_chunk, bypass_flattening)
    shape_ledger = flattener.schema_blueprint.get('reconstruction_mapping', {})
    
    if keep_flattener:
        first_chunk = flattener.transform(first_chunk)

    # B. Optimizer Self-Firing & Semantic Ledger/Header Cache Extraction
    optimizer = SchemaOptimizer()
    _, keep_optimizer, precomputed_headers = optimizer.evaluate(first_chunk, bypass_optimization)
    # Assuming Optimizer exposes its Translation Ledger as an attribute after evaluation
    semantic_ledger = getattr(optimizer, 'translation_ledger', {}) 
    
    if keep_optimizer:
        first_chunk.columns = precomputed_headers

    # C. AI Blueprint Generation (Loop-Less MapReduce)
    final_blueprint = {}
    if mode in ['auto', 'hybrid']:
        scanner = DataScanner()
        first_chunk_stats = extract_chunk_statistics(first_chunk)
        all_mapped_stats = [first_chunk_stats]

        runner = UniversalParallelRunner(max_workers=max_cores)
        
        # Parallel pass over chunks 2-N using strict C-level multiprocessing
        mapped_results, _ = runner.execute(
            func=_pass1_discovery_worker, # Assumed internal mapped function
            payload=chunk_generator,
            keep_flat=keep_flattener,
            keep_opt=keep_optimizer,
            flat_blueprint=flattener.schema_blueprint,
            opt_headers=precomputed_headers
        )
        all_mapped_stats.extend(mapped_results)
        
        # Global Reduce
        scanner.reduce_stats(all_mapped_stats)
        ai_blueprint = scanner.generate_blueprint()
        
        # Hybrid Overrides
        if mode == 'hybrid':
            # _deep_merge_blueprints merges nested dicts efficiently
            final_blueprint = _deep_merge_blueprints(ai_blueprint, blueprint or {}) 
        else:
            final_blueprint = ai_blueprint
    else:
        logger.info("AI Heuristics Bypassed. Injecting Strict User Blueprint.")
        final_blueprint = blueprint or {}
        runner = UniversalParallelRunner(max_workers=max_cores)

    # ==========================================
    # PHASE 2: THE ENGINE ROOM (Massive Execution)
    # ==========================================
    logger.info("Phase 1 Complete. Igniting the Parallel Execution Engine...")
    from nullhunter.engine import ExecutionEngine
    from nullhunter.nodes.reconstructor import SchemaReconstructor
    
    # Reset stream cursor for the full data sweep
    loader.reset_stream()
    
    # Calculate RAM Safety Limits
    safe_buffer = buffer_size_mb if buffer_size_mb else loader.calculate_safe_buffer_limit()
    
    # Mount Dependencies (Engine remains dumb and strictly follows orders)
    engine = ExecutionEngine(
        loader_ref=loader,
        reconstructor_ref=SchemaReconstructor(),
        parallel_runner_ref=runner,
        write_buffer_limit_mb=safe_buffer,
        max_cores=max_cores
    )
    
    # Unleash Execution (Passing Caches and Ledgers for O(1) Speed)
    telemetry = engine.execute_pipeline(
        destination=destination,
        blueprint=final_blueprint,
        shape_ledger=shape_ledger,           # Asset 1 (For Reconstructor)
        semantic_ledger=semantic_ledger,     # Asset 2 (For Reconstructor)
        precomputed_headers=precomputed_headers if keep_optimizer else None, # For Flattener O(1) wrap
        keep_optimized_headers=keep_optimized_headers,
        fail_fast=fail_fast
    )
    
    # Final Metric Compilation
    telemetry["api_execution_mode"] = str(mode)
    telemetry["total_time_sec"] = round(time.perf_counter() - start_time, 4)
    
    logger.info("Supreme Commander Signing Off. NullHunter Purification complete.")
    return telemetry


    