"""
NullHunter Schema Reconstructor
==================================================

This module acts as the independent Phase-3 exit node for the NullHunter framework.
It performs an O(1) reverse-transformation of the metadata (Headers and Row Indices),
restoring the processed 2D chunks back to their exact original multi-dimensional 
hierarchical shapes (MultiIndex) before they are flushed to disk.

Key Architectural Pillars:
1. Zero-Cost Abstraction: Manipulates only metadata, never iterating over rows.
2. Complete Decoupling: Can be used entirely outside the NullHunter ecosystem.
3. Consent-Driven Mutation: Adheres strictly to the `keep_optimized_headers` flag.
"""

import time
import logging
import pandas as pd
from typing import Dict, Any

# ==========================================
# LOGGER CONFIGURATION
# ==========================================
logger = logging.getLogger(__name__)

class NullHunterReconstructionError(Exception):
    """Raised when the reconstructor fails to resolve ledger mapping safely."""
    pass


class SchemaReconstructor:
    """
    DataFrame Shape Restorer.
    
    Transforms flattened ML-ready DataFrames back into their original, 
    human-readable, complex hierarchical shapes based on a Master Ledger.
    """
    
    def __init__(self, strict_validation: bool = False):
        """
        Initializes the Reconstructor.
        
        Args:
            strict_validation (bool): If True, raises errors when missing columns 
                are detected. If False, gracefully skips them (useful for dynamic 
                dropping during execution). Defaults to False.
        """
        self.strict_validation = strict_validation
        logger.debug(f"SchemaReconstructor initialized. Strict Mode: {self.strict_validation}")

    def rebuild(
        self,
        chunk: pd.DataFrame,
        master_ledger: Dict[str, Any],
        keep_optimized_headers: bool = False,
        inplace: bool = False,
        drop_unmapped: bool = False,
        unnamed_fill_value: str = ""
    ) -> pd.DataFrame:
        """
        The Master Reconstruction Protocol.
        
        Applies reverse-mapping to restore MultiIndex columns and Row Indices in O(1) time.
        
        Args:
            chunk (pd.DataFrame): The processed, flat 2D dataframe chunk.
            master_ledger (Dict[str, Any]): The reverse mapping dictionary generated by Pass-1.
                Expected to contain an '__index_names__' key for row index mapping.
            keep_optimized_headers (bool, optional): If True, retains the flat, clean headers 
                created by the optimizer, only restoring the row indices. Defaults to False.
            inplace (bool, optional): If True, mutates the chunk in memory to save RAM. 
                Defaults to False.
            drop_unmapped (bool, optional): If True, deletes any newly generated temporary 
                columns that do not exist in the master ledger. Defaults to False.
            unnamed_fill_value (str, optional): The value used to replace 'UNNAMED_LEVEL' 
                placeholders in MultiIndex levels. Defaults to an empty string "".
                
        Returns:
            pd.DataFrame: The structurally reconstructed dataframe ready for Disk I/O.
            
        Raises:
            NullHunterReconstructionError: If structural integrity checks fail under strict mode.
        """
        start_time = time.perf_counter()
        
        # 1. The O(1) Bypass (If data was already perfect or turbo mode is on)
        if not master_ledger:
            return chunk if inplace else chunk.copy(deep=False)

        # 2. Memory Management
        df = chunk if inplace else chunk.copy(deep=False)

        # 3. Garbage Collection (Optional Temporary Column Cleanup)
        if drop_unmapped:
            mapped_keys = set(master_ledger.keys())
            # We don't drop columns that were explicitly flagged as row indices
            index_registry = master_ledger.get("__index_names__", [])
            cols_to_drop = [
                c for c in df.columns 
                if c not in mapped_keys and c not in index_registry
            ]
            if cols_to_drop:
                df.drop(columns=cols_to_drop, inplace=True)
                logger.debug(f"Dropped {len(cols_to_drop)} unmapped temporary columns.")

        # 4. Row Index Resurrection
        # Extracts the secret '__index_names__' list stored by the Flattener
        index_cols = master_ledger.get("__index_names__", [])
        actual_index_cols = [col for col in index_cols if col in df.columns]
        
        if actual_index_cols:
            df.set_index(actual_index_cols, inplace=True)
            
            # Restore the original beautiful names for the row indices
            restored_index_names = []
            for idx in actual_index_cols:
                orig_mapping = master_ledger.get(idx, idx)
                # If the original index name was a tuple, grab the most specific level
                if isinstance(orig_mapping, tuple):
                    restored_index_names.append(orig_mapping[-1])
                else:
                    restored_index_names.append(orig_mapping)
            
            df.index.names = restored_index_names

        # 5. Column Header Strategy (Consent-Driven)
        if keep_optimized_headers:
            # User wants to keep the clean ML-ready names. We exit early!
            return df
            
        # 6. MultiIndex Header Restoration
        new_columns = []
        is_hierarchical = False
        
        for col in df.columns:
            # Fallback to current name if missing in ledger (graceful degradation)
            original_shape = master_ledger.get(col, col)
            
            if self.strict_validation and col not in master_ledger:
                raise NullHunterReconstructionError(
                    f"Strict Mode Violation: Column '{col}' missing from Master Ledger."
                )

            if isinstance(original_shape, tuple):
                is_hierarchical = True
                # Clean up the ugly 'UNNAMED_LEVEL' placeholders
                cleaned_tuple = tuple(
                    unnamed_fill_value if "UNNAMED_LEVEL" in str(lvl) else lvl 
                    for lvl in original_shape
                )
                new_columns.append(cleaned_tuple)
            else:
                new_columns.append(original_shape)

        # 7. Apply the Final Shape
        if is_hierarchical:
            # Normalize mixed flat and tuple names into consistent tuples
            normalized_cols = [
                c if isinstance(c, tuple) else (c,) 
                for c in new_columns
            ]
            df.columns = pd.MultiIndex.from_tuples(normalized_cols)
        else:
            df.columns = new_columns

        exec_time = (time.perf_counter() - start_time) * 1000
        logger.debug(f"Chunk reconstructed in {exec_time:.2f} ms.")

        return df
    